
import { UserInfo, Grade, GradesResponse } from './api';

// Mock user info
export const mockUserInfo: UserInfo = {
  studentLoginId: 123456,
  studentId: 789012,
  id: "+aeBzXT1lJWeII7SU8zhXQ==",
  userId: "vapVfWZSrkAZCgzVeS8MnpaNgRVtR6WSLM9DJJzchdQ=",
  schoolName: "חטב ליאו בק",
  mustChangePassword: false,
  userType: 0,
  userImageToken: "e3f98d5845b305ef0642105fcfeb3dac3a4e962a",
  fullLog: false,
  firstName: "אייל יעקב",
  lastName: "מירום",
  isTeacher: 0,
  isWebTopUser: true,
  schoolId: 1406,
  studentEmail: null,
  studentGender: false,
  firstInstitutionCode: 344093,
  institutionCode: 344093,
  isReseted: false,
  lastResetDate: "2023-08-15T23:01:00",
  lastPasswordChangeDate: "2025-04-09T11:27:00",
  lastLoginDate: "2025-05-19T16:15:00",
  classCode: "8",
  classNumber: 4,
  isSchoolyAdministrator: false,
  token: "W/T/KaL70Rj8h9Lt7WZn4hTdj2/259fCZ2/U0BZk/1n...",
  cellphone: "0546920670",
  browserLanguage: null,
  initialUserType: 0,
  fullName: "מירום אייל יעקב"
};

// Mock user image URL
export const mockUserImage = "https://randomuser.me/api/portraits/men/42.jpg";

// Mock grades for period 1
const mockGradesPeriod1: Grade[] = [
  {
    evaluationID: 2671090,
    title: "עבודת קיץ",
    date: "2024-09-12T00:00:00",
    type: "עבודה",
    typeCode: 5,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 100,
    gradeTranslation: "מצויין",
    subject: "מתמטיקה",
    level: "",
    weight: 20,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671091,
    title: "מבחן פרק א",
    date: "2024-10-15T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 85,
    gradeTranslation: "טוב מאוד",
    subject: "מתמטיקה",
    level: "",
    weight: 30,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671092,
    title: "בוחן אמצע מחצית",
    date: "2024-11-05T00:00:00",
    type: "בוחן",
    typeCode: 2,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 92,
    gradeTranslation: "טוב מאוד",
    subject: "מתמטיקה",
    level: "",
    weight: 10,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671093,
    title: "מבחן מחצית",
    date: "2024-12-20T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 88,
    gradeTranslation: "טוב מאוד",
    subject: "מתמטיקה",
    level: "",
    weight: 40,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671094,
    title: "עבודה מסכמת",
    date: "2024-09-05T00:00:00",
    type: "עבודה",
    typeCode: 5,
    teacherFirstName: "רונית",
    teacherLastName: "כהן",
    grade: 95,
    gradeTranslation: "מצויין",
    subject: "אנגלית",
    level: "5 יח\"ל",
    weight: 15,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671095,
    title: "מבחן אמצע",
    date: "2024-10-25T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "רונית",
    teacherLastName: "כהן",
    grade: 90,
    gradeTranslation: "טוב מאוד",
    subject: "אנגלית",
    level: "5 יח\"ל",
    weight: 30,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671096,
    title: "פרזנטציה",
    date: "2024-11-10T00:00:00",
    type: "פרזנטציה",
    typeCode: 3,
    teacherFirstName: "רונית",
    teacherLastName: "כהן",
    grade: 98,
    gradeTranslation: "מצויין",
    subject: "אנגלית",
    level: "5 יח\"ל",
    weight: 10,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671097,
    title: "מבחן מחצית",
    date: "2024-12-15T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "רונית",
    teacherLastName: "כהן",
    grade: 92,
    gradeTranslation: "טוב מאוד",
    subject: "אנגלית",
    level: "5 יח\"ל",
    weight: 40,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671098,
    title: "מבחן מבוא לפיזיקה",
    date: "2024-10-10T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "אבי",
    teacherLastName: "לוי",
    grade: 78,
    gradeTranslation: "כמעט טוב",
    subject: "פיזיקה",
    level: "5 יח\"ל",
    weight: 30,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671099,
    title: "מבחן אמצע מחצית",
    date: "2024-11-20T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "אבי",
    teacherLastName: "לוי",
    grade: 85,
    gradeTranslation: "טוב מאוד",
    subject: "פיזיקה",
    level: "5 יח\"ל",
    weight: 35,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671100,
    title: "השתתפות וידע",
    date: "2024-12-01T00:00:00",
    type: "השתתפות",
    typeCode: 4,
    teacherFirstName: "עמית",
    teacherLastName: "נווה",
    grade: 97,
    gradeTranslation: "מצויין",
    subject: "היסטוריה",
    level: "",
    weight: 10,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671101,
    title: "עבודת חקר",
    date: "2024-11-15T00:00:00",
    type: "עבודה",
    typeCode: 5,
    teacherFirstName: "עמית",
    teacherLastName: "נווה",
    grade: 92,
    gradeTranslation: "טוב מאוד",
    subject: "היסטוריה",
    level: "",
    weight: 30,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671102,
    title: "מבחן מסכם",
    date: "2024-12-20T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "עמית",
    teacherLastName: "נווה",
    grade: 88,
    gradeTranslation: "טוב",
    subject: "היסטוריה",
    level: "",
    weight: 55,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2671103,
    title: "תרגילים 1-5",
    date: "2024-09-30T00:00:00",
    type: "עבודה",
    typeCode: 5,
    teacherFirstName: "יעל",
    teacherLastName: "שמואלי",
    grade: 80,
    gradeTranslation: "טוב",
    subject: "תנ\"ך",
    level: "",
    weight: 20,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1538,
    componentsWeightInPer: true
  }
];

// Mock grades for period 2
const mockGradesPeriod2: Grade[] = [
  {
    evaluationID: 2679001,
    title: "מבחן פתיחת מחצית",
    date: "2025-01-15T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 88,
    gradeTranslation: "טוב מאוד",
    subject: "מתמטיקה",
    level: "",
    weight: 30,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679002,
    title: "בוחן מתכונת",
    date: "2025-02-10T00:00:00",
    type: "בוחן",
    typeCode: 2,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 90,
    gradeTranslation: "טוב מאוד",
    subject: "מתמטיקה",
    level: "",
    weight: 20,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679003,
    title: "מבחן סיום",
    date: "2025-03-20T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 94,
    gradeTranslation: "מצויין",
    subject: "מתמטיקה",
    level: "",
    weight: 30,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679004,
    title: "פרוייקט גמר",
    date: "2025-03-28T00:00:00",
    type: "פרויקט",
    typeCode: 6,
    teacherFirstName: "ליאור",
    teacherLastName: "סגל",
    grade: 97,
    gradeTranslation: "מצויין",
    subject: "מתמטיקה",
    level: "",
    weight: 10,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679005,
    title: "מבחן ספרות",
    date: "2025-02-05T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "רונית",
    teacherLastName: "כהן",
    grade: 87,
    gradeTranslation: "טוב",
    subject: "אנגלית",
    level: "5 יח\"ל",
    weight: 30,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679006,
    title: "עבודת סיכום",
    date: "2025-03-15T00:00:00",
    type: "עבודה",
    typeCode: 5,
    teacherFirstName: "רונית",
    teacherLastName: "כהן",
    grade: 93,
    gradeTranslation: "טוב מאוד",
    subject: "אנגלית",
    level: "5 יח\"ל",
    weight: 25,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679007,
    title: "בחינת הבנת הנקרא",
    date: "2025-03-25T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "רונית",
    teacherLastName: "כהן",
    grade: 95,
    gradeTranslation: "מצויין",
    subject: "אנגלית",
    level: "5 יח\"ל",
    weight: 35,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679008,
    title: "מבחן אמצע מחצית",
    date: "2025-02-15T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "אבי",
    teacherLastName: "לוי",
    grade: 92,
    gradeTranslation: "טוב מאוד",
    subject: "פיזיקה",
    level: "5 יח\"ל",
    weight: 40,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679009,
    title: "מעבדה",
    date: "2025-03-10T00:00:00",
    type: "עבודה",
    typeCode: 5,
    teacherFirstName: "אבי",
    teacherLastName: "לוי",
    grade: 95,
    gradeTranslation: "מצויין",
    subject: "פיזיקה",
    level: "5 יח\"ל",
    weight: 15,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679010,
    title: "פרזנטציה",
    date: "2025-01-20T00:00:00",
    type: "פרזנטציה",
    typeCode: 3,
    teacherFirstName: "עמית",
    teacherLastName: "נווה",
    grade: 96,
    gradeTranslation: "מצויין",
    subject: "היסטוריה",
    level: "",
    weight: 25,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  },
  {
    evaluationID: 2679011,
    title: "מבחן מסכם",
    date: "2025-03-18T00:00:00",
    type: "מבחן",
    typeCode: 1,
    teacherFirstName: "עמית",
    teacherLastName: "נווה",
    grade: 92,
    gradeTranslation: "טוב מאוד",
    subject: "היסטוריה",
    level: "",
    weight: 70,
    remark: null,
    assessment: null,
    assessmentId: null,
    components: [],
    componentComment: null,
    componentAssement: null,
    reExaminationRequestLastDate: null,
    reExaminationDate: null,
    reExaminationNote: null,
    isDeleted: 0,
    period_id: 1539,
    componentsWeightInPer: true
  }
];

// Mock grades responses
export const mockGradesResponsePeriod1: GradesResponse = {
  status: true,
  data: mockGradesPeriod1,
  message: null,
  errorId: null,
  errorDescription: null,
  errorHTML: null
};

export const mockGradesResponsePeriod2: GradesResponse = {
  status: true,
  data: mockGradesPeriod2,
  message: null,
  errorId: null,
  errorDescription: null,
  errorHTML: null
};

// Create a mock api service using the mock data
export const mockApiService = {
  login: async (credentials: { username: string; password: string }) => {
    // Simulate successful login with any credentials
    console.log('Mock login with credentials:', credentials);
    return { success: true };
  },
  
  logout: async () => {
    console.log('Mock logout');
    return { success: true };
  },
  
  getUserInfo: async () => {
    console.log('Mock getUserInfo');
    return mockUserInfo;
  },
  
  getUserImage: async () => {
    console.log('Mock getUserImage');
    return mockUserImage;
  },
  
  getGradesPeriod1: async () => {
    console.log('Mock getGradesPeriod1');
    return mockGradesResponsePeriod1;
  },
  
  getGradesPeriod2: async () => {
    console.log('Mock getGradesPeriod2');
    return mockGradesResponsePeriod2;
  }
};
